# Generated by Django 5.2.7 on 2025-11-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('description', models.TextField(verbose_name='Descripción del Producto')),
                ('category', models.CharField(choices=[('EL', 'Electronics'), ('FA', 'Fashion'), ('HO', 'Home'), ('TO', 'Toys'), ('SP', 'Sports')], default='HO', max_length=2, verbose_name='Categoría')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad en Stock')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['stock_quantity'], name='products_pr_stock_q_ba97b5_idx'), models.Index(fields=['category'], name='products_pr_categor_14b9c0_idx'), models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'), models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx')],
            },
        ),
    ]
