# Generated by Django 5.2.7 on 2025-11-29 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_stock_q_ba97b5_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
    ]
